config/routes.rb
MissionaryWebsite4::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/store'

  resources :contacts

  match 'aboutus-us' => 'home#aboutus', :via => [:get], :as => 'about_us'
  match 'privacy' => 'home#privacy', :via => [:get], :as => 'privacy'
  match 'warranty' => 'home#warranty', :via => [:get], :as => 'warranty'
  match 'resellers' => 'home#resellers', :via => [:get], :as => 'resellers'
  match 'almost_finished' => 'home#almost_finished', :via => [:get], :as => 'almost_finished'
  match '' => 'home#index', :via => [:get], :as => 'home'
  resources :hoggans_construction, :only => [:index, :update]
  resources :home do
    member do
      get 'price'
    end
  end
  root :to => 'home#index' 
end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :add_ons
    end
    resources :reports, :only => [] do
      collection do

        get   :idaho_taxes
        post  :idaho_taxes

      end
    end
    resources :workflows, :only => [:index, :update] do 
      collection do 
        put "update_all"
        get "authenticate"
        put "bluedot"
        get "oauth_callback"
        get "export_to_quickbooks"

      end
      member do
        get "packing_slip"
        get "shipping"
        post "rates"
        get "print_postage"
        post "purchase_postage"
        get "update_shipment"
        get "update_order"
        post 'show_to_hoggans'
        patch 'show_to_hoggans'
      end
    end
  end
end

  

app/controllers/spree/admin/workflows_controller.rb
module Spree
  module Admin
    class WorkflowsController < Spree::Admin::BaseController
			require 'easypost_api'

			skip_before_filter :authenticate_user!, :only => [:index, :update]

    	layout "workflow"

    	before_filter :load_options

			def index
				@orders = Spree::Order.where("state = 'complete' AND NOT shipment_state	= 'shipped'").order("created_at ASC")
				# Create Manufacture Status for each item
				@orders.each do |order|
					order.line_items.each do |item|
						if !item.manufacture_status
							ManufactureStatus.create(:line_item => item)
						end
					end
				end
				@orders.reload

			end

			def update
				line_item_id = params[:id] 
				ap line_item_id

				line_item = LineItem.find(line_item_id)
				ap params
				ap params["manufacture_status"]
				ap params["manufacture_status"]["status"]
				line_item.manufacture_status.status = params["manufacture_status"]["status"]
				
				if line_item.save
					render :json => {:result => "success", :html => ""}
				else
					render :json => {:result => "failed", :html => ""}
				end
			end

			def update_order
				@order = Spree::Order.find_by_number(params[:id])
				@order.update!
				redirect_to edit_admin_order_path(@order.number)
			end

			def packing_slip
				@order = Spree::Order.find_by_number(params[:id])
			end

			def shipping

				@order = Spree::Order.find_by_number(params[:id])

				if @order.postage_id.present?
					redirect_to print_postage_admin_workflow_path
				else
					@weight = EasypostApi.order_weight(@order)
					@width = EasypostApi.box_width(@order)
					@height = EasypostApi.box_height(@order)
					@length = EasypostApi.box_length(@order)
					# @rates = EasypostApi.get_rates(@order)
				end
				
			end

			def rates
				@order = Spree::Order.find_by_number(params[:id])
				@weight = params["weight"]
				@width = params[:width]
				@height = params[:height]
				@length = params[:length]
				residential = params["is_residential"]

				ap residential
				ap residential == "1" ? true : false
				@rates = EasypostApi.get_custom_rates(@order, @weight.to_d * 16, @width.to_d, @length.to_d, @height.to_d, residential == "1" ? true : false)
				render :partial => "rates", :locals => {:rates => @rates, :order => @order} 
			end

			def purchase_postage
				@order = Spree::Order.find_by_number(params[:id])
				
				EasypostApi.purchase_postage(@order, params["shipment_id"], params["rate_id"])

				render "print_postage"
			end

			def print_postage
				@order = Spree::Order.find_by_number(params[:id])
			end

			def update_shipment
				@order = Spree::Order.find_by_number(params[:id])
				EasypostApi.update_postage(@order)				
				render "print_postage"
			end

			def load_options
				@status_options = [
                                  ['From Inventory', 'inventory'],
                                  ['Acknowledged', 'acknowledged'],
                                  ['Begin Manufacture', 'begunManuf'],
                                  ['Completed Manufacture', 'completedManuf'],
                                  ['Delivered', 'delivered']
                                ]
			end

			# Used for QuickeeBooks
			def authenticate
				ap params
		    callback = oauth_callback_admin_workflows_url
		    token = $qb_oauth_consumer.get_request_token(:oauth_callback => callback)
		    session[:qb_request_token] = token
		    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
		  end			

		  def bluedot
			  # I am saving access_token and access_secret in company table so I will fetch from there
			  access_token = current_company.access_token
			  access_secret = current_company.access_secret
			  consumer = OAuth::AccessToken.new($qb_oauth_consumer, access_token, access_secret)
			  response = consumer.request(:get, "https://appcenter.intuit.com/api/v1/Account/AppMenu")
			  if response && response.body
			    html = response.body
			    render(:text => html) and return
			  end
			end

			def show_to_hoggans
				@order = Spree::Order.find_by_number(params[:id])
				show_hoggans = params[:order][:force_to_hoggan]
				@order.update_attributes(:force_to_hoggan => show_hoggans)
				if show_hoggans
					Notifier.hoggans_order_created(@order).deliver_now
				end
				redirect_to :back
			end

			def oauth_callback
		    at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
		    token = at.token
		    secret = at.secret
		    realm_id = params['realmId']
		    ap token
		    ap secret
		    ap realm_id
		    qc = QuickbooksConnection.first
		    # store the token, secret & RealmID somewhere for this user, you will need all 3 to work with Quickeebooks
		    if qc 
		    	qc.update_attributes(:token => token, :secret => secret, :realm_id => realm_id)
		    else
		    	qc = QuickbooksConnection.create(:token => token, :secret => secret, :realm_id => realm_id)
		    end
		    
		    # Save the Base URL
		    consumer = OAuth::AccessToken.new($qb_oauth_consumer, token, secret)
			  response = consumer.request(:get, "https://qbo.intuit.com/qbo1/rest/user/v2/" + realm_id)

			  base = (Hash.from_xml response.body)["QboUser"]["CurrentCompany"]["BaseURI"]
			  qc.update_attributes(:base_uri => base)	
			end

			def export_to_quickbooks
				# If order has user, check if the user has been exported to the customer table
				qc = QuickbooksConnection.first
				oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, qc.token, qc.secret)

				# For each non-exported completed Order, export it to quickbooks
				orders = Spree::Order.complete.where("exported_to_quickbooks is false AND shipment_state = 'shipped'")

				
				orders.each do |order|
				# order = orders[0]
					order_email = Quickeebooks::Online::Model::Email.new(order.email)
					
					customer_service = Quickeebooks::Online::Service::Customer.new
					customer_service.access_token = oauth_client
					customer_service.realm_id = qc.realm_id
					customer_service.list

					customer = Quickeebooks::Online::Model::Customer.new
					full_name = "#{order.billing_address.firstname} #{order.billing_address.lastname}"
					customer.name = "#{full_name} - #{order.number}"
					customer.given_name = order.billing_address.firstname
					customer.family_name = order.billing_address.lastname
					customer.email = order_email
					customer.dba_name = full_name
					
					begin
						c = customer_service.create(customer)	
						order.update_attribute(:quickbooks_customer_id, c.id)				
					rescue Exception => error
						ap error
						# User already exists, go find it
						customer_service = Quickeebooks::Online::Service::Customer.new
						customer_service.access_token = oauth_client
						customer_service.realm_id = qc.realm_id
						customer_service.list

						filters = []
						filters << Quickeebooks::Shared::Service::Filter.new(:text, :field => 'Name', :value => "#{full_name} - #{order.number}")

						found_custs = customer_service.list(filters)
						if found_custs.count == 1
							c = found_custs.entries.first
						end
					end

					invoice_service = Quickeebooks::Online::Service::Invoice.new
					invoice_service.access_token = oauth_client
					invoice_service.realm_id = qc.realm_id
					invoice_service.list

					invoice = Quickeebooks::Online::Model::Invoice.new
					# Create Line Items
					line_items = []
					order.line_items.each do |li|
						invoice_li = Quickeebooks::Online::Model::InvoiceLineItem.new
						invoice_li.desc = li.variant.product.name
						invoice_li.amount = li.price
						# invoice_li.item_id = Quickeebooks::Online::Model::Id.new(li.variant.product.id)
						invoice_li.unit_price = li.price
						invoice_li.quantity = li.quantity
						
						line_items << invoice_li
					end
					invoice.line_items = line_items

ap c
ap c.id
ap order
					# Create Header
					invoice_header = Quickeebooks::Online::Model::InvoiceHeader.new
					invoice_header.customer_id = Quickeebooks::Online::Model::Id.new(c.id)
					invoice_header.customer_name = c.name 
					# missionary bag class_id
					invoice_header.class_id = Quickeebooks::Online::Model::Id.new(100000000000344410)  
					invoice_header.ship_date = order.updated_at.time
					invoice_header.sub_total_amount = order.item_total
					invoice_header.total_amount = order.total
					invoice_header.txn_date = order.updated_at.time
					invoice_header.due_date = order.updated_at.time

					billing_address = Quickeebooks::Online::Model::Address.new
					billing_address.line1 = order.billing_address.address1
					billing_address.line2 = order.billing_address.address2
					billing_address.city = order.billing_address.city
					billing_address.country_sub_division_code = order.billing_address.state.name
					billing_address.country = order.billing_address.country.iso3
					billing_address.postal_code = order.billing_address.zipcode
					invoice_header.billing_address = billing_address
					
					shipping_address = Quickeebooks::Online::Model::Address.new
					shipping_address.line1 = order.shipping_address.address1
					shipping_address.line2 = order.shipping_address.address2
					shipping_address.city = order.shipping_address.city
					shipping_address.country_sub_division_code = order.shipping_address.state.name
					shipping_address.country = order.shipping_address.country.iso3
					shipping_address.postal_code = order.shipping_address.zipcode
					invoice_header.shipping_address = shipping_address

					invoice_header.bill_email = order.email
					invoice.header = invoice_header
					i = invoice_service.create(invoice)

					order.quickbooks_invoice_id = c.id
					unless o = order.save
						ap "There was a problems saving the order #{order.id} quickbooks_id."
					end

					# Register that a payment has gone through
					# Create payment
					payment_service = Quickeebooks::Online::Service::Payment.new
					payment_service.access_token = oauth_client
					payment_service.realm_id = qc.realm_id
					payment_service.list

app/views/spree/admin/workflows/_rates.html.erb
	<table>
		<thead>
			<tr>
				<th colspan=2>Carrier</th>
				<th>Service</th>
				<th>Rate</th>
				<th>Select</th>
				
			</tr>
		</thead>

		<% for rate in rates %>  
			<tr class="order">
				<td><%= rate.carrier %></td>
				<td><%= rate.service %></td>
				<td class="date"><%= rate.rate %></td>
				<td class="status-buttons">
					<%= form_tag purchase_postage_admin_workflow_path(order), :class => "print_postage_form" do %>
						<input type="hidden" name="shipment_id" value="<%= rate.shipment_id %>">
						<input type="hidden" name="rate_id" value="<%= rate.id %>">
						<%= submit_tag "Print Postage" %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</table>

app/views/spree/admin/workflows/index.html.erb
<h1 class="center">Build Status</h1>
<table>
	<thead>
		<tr>
			<th colspan=2>Order</th>
			<th>Date</th>
			<th>Product</th>
			<th>Status</th>
			<th>Status Updated</th>
			<th>Packing Slip</th>
		</tr>
	</thead>

<% for order in @orders %>  
	<% for line_item in order.line_items %>
			<tr class="order">
				<td></td>
				<td class="order-num">#<%= order.number %></td>
				<td class="date"><%= l order.created_at.to_date %></td>
				<td class="product"><%= line_item.product.name %></td>
				<td class="status line-item-status">
					<%= form_for line_item.manufacture_status, :url => admin_workflow_path(line_item.id) do |m| %>
		
						<%= m.select :status, @status_options, options = {:prompt => "Select status..."}, { :class => "select-control select-case-status select2" } %>
					<% end %>
				</td>
				<td class="status-buttons"><%= l line_item.manufacture_status.updated_at %></td>
				<td class="status-buttons"></td>
			</tr>
		
	<% end %>

	<!-- order notes -->
	<% if order.notes && order.notes.count > 0 %>
		<div class="notes">
			<% for note in order.notes %>
				<div class="note">
					<%= note.note %>
				</div>
			<% end %>
		</div>
	<% end %>

<% end %>
</table>

<script type='text/javascript' src='https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js'></script>

	<!-- configure the Intuit object: 'grantUrl' is a URL in your application which kicks off the flow, see below -->
	<script>
	intuit.ipp.anywhere.setup({menuProxy: 'https://appcenter.intuit.com/api/v1/Account/AppMenu', grantUrl: '<%= authenticate_admin_workflows_url %>'});
	</script>

	<!-- this will display a button that the user clicks to start the flow -->
	<ipp:connectToIntuit></ipp:connectToIntuit>

app/views/spree/admin/workflows/oauth_callback.html.erb
Congrats!! You have successfully connected to the Quickbooks Online. We have saved your info in the database for later retrieval. Good luck and happy selling.

app/views/spree/admin/workflows/packing_slip.html.erb
<style>
.center{text-align: center !important;}
.left{text-align: left !important;}
td{
	vertical-align: top;

}
td, h1, h2, h3, div{
	color: #000;
}
#productTable{width:100%;}
div table:nth-child(1n) td:nth-child(2n+1){font-weight: bold;}
table th{text-align: center;}
table th:nth-child(1){width: 17%;}
table th:nth-child(3){width: 10%;}
table th:nth-child(4){width: 13%;}
#productTable td{text-align: right;}
table td, table th{padding:5px;}
table.product th,.total td{border:1px solid black;}
table th{border-left:0px solid white !important;}
table th:first-child{border-left:1px solid black !important;}
table th:nth-child(1n),.total td:nth-child(1n){border-right:1px solid black;}
table th:last-child,.total td:last-child{border-right:1px solid black;}
table:last-child tr:first-child td:first-child,.product td:first-child{border-left:1px solid black !important;}
table:last-child tr:first-child td:last-child,.product td:last-child{border-right:1px solid black !important;}
table thead tr th{ border: 1px solid black; }
.product:last-child td:nth-child(1){border-bottom:1px solid black !important;}
table.product tbody tr:first-child th, table.product tbody tr:first-child td, .product td{
	border-right:1px solid black;
	border-bottom:1px solid black;
	font-weight: normal !important;
}
.product.last td{ border-bottom: 1px solid black;}
.blank{border:0px !important; border-bottom: none;}
.blank.last{border-right:1px solid black !important;}

.total:last-child td:nth-child(3),.total:last-child td:nth-child(4),.total:last-child td:nth-child(5){
	border-bottom:1px solid black !important;
}
.total td{border-left:0px !important;border-bottom:0px !important;font-weight:bold !important;}
.title-bar{ display: inline-block;}
.subtitle{ font-style: italic; font-size: 24px;}
.left{ text-align: left;}

</style>

<div style="width:1000px;margin:auto;padding:50px;border:1px solid #CCC;font-family:Arial, Helvetica, sans-serif;line-height:1.6em;">
	<div class="title-bar">
		<%= image_tag('Missionary_bag_logo_FIN-600px.png', :height => '90px') %>
	</div>
	<div style="float:right;text-align:center;">
		<h1 style="font-size:2.3em;">Packing Slip</h1>
		<%= Date.today.to_formatted_s(:long_ordinal) %>
	</div>
	<div>
		<h2 class="subtitle" >Bags for Missionaries by Missionaries</h2>
	</div>
	<table style="width:100%;">
		<tr>
			<td style="width:25%;">Address:</td>
			<td>140 E 100 S<br>
				Burley, ID 83318<br>
				Phone: 269-350-4760</td>
			<td style="width:25%;">Ship to:</td>
			<td><%= "#{ @order.ship_address.first_name } #{ @order.ship_address.last_name }" %><br>
				<%= @order.ship_address.address1 %><br>
				<% if @order.ship_address.address2.present? %>
					<%= @order.ship_address.address2 %><br>
				<% end %>
				<%= "#{@order.ship_address.city}, #{@order.ship_address.state} #{@order.ship_address.zipcode}" %><br>
				<%= @order.ship_address.phone %><br>
				<%= @order.email %>
			</td>
		</tr>
		<tr>
			<td>Order Date:</td>
			<td><% if @order.completed_at %>
					<%= @order.completed_at.strftime("%B %e, %Y") %>
				<% end %>
			</td>
			<td colspan=2></td>
		</tr>
		<tr>
			<td>Order Number:
				</td>
			<td><%= @order.number%><br>
				<!-- Purchase Order --></td>
			<td>Bill to:</td>
			<td><%= "#{ @order.bill_address.first_name } #{ @order.bill_address.last_name }" %><br>
				<%= @order.bill_address.address1 %><br>
				<% if @order.bill_address.address2.present? %>
					<%= @order.bill_address.address2 %><br>
				<% end %>
				<%= "#{@order.bill_address.city}, #{@order.bill_address.state} #{@order.bill_address.zipcode}" %><br>
				<%= @order.bill_address.phone %><br>
				<%= @order.email %>
			</td>
		</tr>
	</table>
	<br>
	<table cellpadding="0" cellspacing="0" id="productTable">
		<thead>
			<tr>
				<th>Product</th>
				<th>Description</th>
				<th>Price</th>
				<th>Order Quanity</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			<%
			item_count = 0
			for line_item in @order.line_items
				item_count += line_item.quantity
				%>
				<tr class="product">
					<td class="center"><%= line_item.variant.sku %></td>
					<td class="left"><%= line_item.variant.product.name %><br>
						<%= line_item.variant.options_text %>
						<%= render :partial => "spree/add_ons/line_item_add_on_desc", :locals => { :line_item => line_item, :hide_amount => false } %>
					</td>
					<td><%= number_to_currency(line_item.price) %><% line_item.line_item_add_ons.each do |lion| %><% if lion.selected %><br>+ <%= number_to_currency(lion.price) %>
							<% end %>
						<% end %>
					</td>
					<td><%= line_item.quantity %></td>
					<td><%= number_to_currency(line_item.amount) %></td>
				</tr>
			<% end %>
			<% if @order.line_items.count == 1 && @order.item_total == 100 %>
				<tr class="product">
					<td class="center">BELT</td>
					<td class="left">Removeable Waist Belt</td>
					<td>$10.00</td>
					<td>1</td>
					<td>$10.00</td>
				</tr>
			<% end %>
			<tr class="product last">
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<%
			for adj in @order.all_adjustments %>
				<tr class="total ">
				<td class="blank first"></td>
				<td class="blank first last"></td>
				<td colspan=2 class="left"><%= adj.label %>:</td>

				<td><%= number_to_currency(adj.amount) %></td>
			</tr>
			<% end %>

			<% for ship in @order.shipments %>
				<tr class="total ">
				<td class="blank first"></td>
				<td class="blank first last"></td>
				<td colspan=2 class="left">Shipping:</td>

				<td><%= number_to_currency(ship.cost) %></td>
			</tr>
			<% end %>


			<tr class="total">
				<td class="blank"></td>
				<td class="blank last"></td>
				<td>Total:</td>
				<td><%= item_count %></td>
				<td><%= number_to_currency(@order.total) %></td>
			</tr>
		</tbody>
	</table>
	<br>
	<div style="border:1px solid black;padding:5px;">
		<span class="bold">Comments:</span><br>
		<!-- Comments -->&nbsp;
	</div>
	<br>
	<div class="center">
		Please contact the Customer Service department at <span class="bold">269-350-4760</span> with any questions or concerns.
		<h3>Thank you for your business!</h3>
	</div>
</div>

app/views/spree/admin/workflows/print_postage.html.erb
<h1 class="center">Shipping Rates for order: <%= @order.number %></h1>

<table>
	<thead>
		<tr>
			<th>Field</th>
			<th>Details</th>
		</tr>
	</thead>
	<tr>
		<td>Date:</td>
		<td><%= @order.postage_date %></td>
	</tr>
	<tr>
		<td>postage_id:</td>
		<td><%= @order.postage_id %></td>
	</tr>
	<tr>
		<td>Type:</td>
		<td><%= @order.postage_type %></td>
	</tr>
	<tr>
		<td>File Type:</td>
		<td><%= @order.postage_file_type %></td>
	</tr>
	<tr>
		<td>Postage URL:</td>
		<td><%= link_to @order.postage_url, @order.postage_url, :target => "_blank"  %></td>
	</tr>
	<tr>
		<td>Postage PDF:</td>
		<td><%= if @order.postage_pdf_url.present? 
			link_to @order.postage_pdf_url, @order.postage_pdf_url, :target => "_blank" 
		else
			link_to "Get PDF URL", update_shipment_admin_workflow_path(@order)
		end %>
			</td>
	</tr>	
	<tr>
		<td>Postage ZPL URL:</td>
		<td><%= if @order.postage_zpl_url.present? 
			link_to @order.postage_zpl_url, @order.postage_zpl_url, :target => "_blank"  
			end  %>
		</td>
	</tr>	
	<tr>
		<td>Postage Epl2 URL:</td>
		<td><%= if @order.postage_epl2_url.present? 
			link_to @order.postage_epl2_url, @order.postage_epl2_url, :target => "_blank"  
			end  %>
		</td>
	</tr>

</table>

<%= link_to "< Back to Order", edit_admin_order_path(@order.number) %>

app/views/spree/admin/workflows/shipping.html.erb
<h1 class="center">Shipping Rates for order: <%= @order.number %></h1>
<%= form_tag rates_admin_workflow_path(@order), :class => "rates_form" do %>

  
	<div class="field">
		Weight
		<%= text_field_tag "weight", @weight/16 %>lbs
	</div>
	<div class="field">
		Width
		<%= text_field_tag "width", @width %>in.
	</div>
	<div class="field">
		Length
		<%= text_field_tag "length", @length %>in.
	</div>
	<div class="field">
		Height
		<%= text_field_tag "height", @height %>in.
	</div>
	<div class="field">
		Is residential?
		<%= check_box_tag "is_residential", value="1", checked=true %>
	</div>

	<%= submit_tag "Get Rates" %>
<% end %>
<div class="table-loading">loading...</div>
<div class="rate-table">
	
</div>