config/routes.rb
MissionaryWebsite4::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/store'

  resources :contacts

  match 'aboutus-us' => 'home#aboutus', :via => [:get], :as => 'about_us'
  match 'privacy' => 'home#privacy', :via => [:get], :as => 'privacy'
  match 'warranty' => 'home#warranty', :via => [:get], :as => 'warranty'
  match 'resellers' => 'home#resellers', :via => [:get], :as => 'resellers'
  match 'almost_finished' => 'home#almost_finished', :via => [:get], :as => 'almost_finished'
  match '' => 'home#index', :via => [:get], :as => 'home'
  resources :hoggans_construction, :only => [:index, :update]
  resources :home do
    member do
      get 'price'
    end
  end
  root :to => 'home#index' 
end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :add_ons
    end
    resources :reports, :only => [] do
      collection do

        get   :idaho_taxes
        post  :idaho_taxes

      end
    end
    resources :workflows, :only => [:index, :update] do 
      collection do 
        put "update_all"
        get "authenticate"
        put "bluedot"
        get "oauth_callback"
        get "export_to_quickbooks"

      end
      member do
        get "packing_slip"
        get "shipping"
        post "rates"
        get "print_postage"
        post "purchase_postage"
        get "update_shipment"
        get "update_order"
        post 'show_to_hoggans'
        patch 'show_to_hoggans'
      end
    end
  end
end

  

app/controllers/hoggans_construction_controller.rb
class HoggansConstructionController < ApplicationController
	before_filter :load_options

	def index
		@orders = Spree::Order.where("state = 'complete' AND NOT shipment_state	= 'shipped'").order("created_at ASC")
		# Create Manufacture Status for each item
		@orders.each do |order|
			order.line_items.each do |item|
				if !item.manufacture_status
					ManufactureStatus.create(:line_item => item)
				end
			end
		end
		@orders.reload

	end

	def update
		line_item_id = params[:id] 
		ap line_item_id

		line_item = Spree::LineItem.find(line_item_id)
		ap params
		ap params["manufacture_status"]
		ap params["manufacture_status"]["status"]
		line_item.manufacture_status.status = params["manufacture_status"]["status"]
		
		if line_item.save
			render :json => {:result => "success", :html => ""}
		else
			render :json => {:result => "failed", :html => ""}
		end
	end

	private

	def load_options
		@status_options = [
                              ['From Inventory', 'inventory'],
                              ['Acknowledged', 'acknowledged'],
                              ['Needs Embroidery', 'startEmbroidery'],
                              ['Getting Embroidery', 'gettingEmbroidery'],
                              ['Embroidery Done', 'embroideryDone'],
                              ['Begin Manufacture', 'begunManuf'],
                              ['Completed Manufacture', 'completedManuf'],
                              ['Delivered', 'delivered']
                            ]
	end
end

app/views/hoggans_construction/index.html.erb
<h1 class="center">Build Status</h1>
<table>
	<thead>
		<tr>
			<th>Order</th>
			<th>Date</th>
			<th>Product</th>
			<th>Status</th>
			<th>Status Updated</th>
		</tr>
	</thead>

<% for order in @orders 
		showing_rows = false
%>  
	<% order.line_items.each do |line_item| %>
		<% if (line_item.variant.stock_items.count > 0 && !line_item.variant.stock_items.first.in_stock?) || (line_item.line_item_add_ons.count > 0 && line_item.line_item_add_ons.first.selected || order.force_to_hoggan ) 
				showing_rows == true
			%>
			<tr class="order">
			
				<td class="order-num">#<%= order.number %></td>
				<td class="date"><%= l order.created_at.to_date %></td>
				<td class="product"><%= "#{line_item.quantity > 1 ? "#{line_item.quantity} x " : "" }#{line_item.product.name } #{line_item.variant.options_text}" %></td>
				<td class="status line-item-status">
					<%= form_for line_item.manufacture_status, :url => hoggans_construction_path(line_item.id) do |m| %>
		
						<%= m.select :status, @status_options, options = {:prompt => "Select status..."}, { :class => "select-control select-case-status select2" } %>
					<% end %>
				</td>
				<td class="date"><%= l line_item.manufacture_status.updated_at.to_date %></td>
			</tr>
			<% if order.mission_date.present? %>
				<tr class="note"><td colspan=5>
					<span>Reports to MTC on:</span>
					<%= order.mission_date %>
				</td></tr>	
			<% end %>
			<% if line_item.needs_embroidery? %>
				<tr class="note"><td colspan=5>
					<span><%= line_item.variant.options_text %></span>
					<%= render :partial => "spree/add_ons/line_item_add_on_desc", :locals => { :line_item => line_item, :hide_amount => true } %>
				</td></tr>	
			<% end %>
			<% if order.special_instructions.present? %>
				<tr class="note"><td colspan=5>
					<b>Customer Instructions:</b><%= order.special_instructions %>
				</td></tr>
			<% end %>
			<!-- order notes -->
			<% if order.notes && order.notes.count > 0 %>
				<% for note in order.notes %>
					<tr class="note"><td colspan=5>
						<%= note.note %>
					</td></tr>
				<% end %>
			<% end %>
			<% if order.comments && order.comments.count > 0 %>
				<% for comment in order.comments %>
					<tr class="comment"><td colspan=5>
						<%= comment.comment %>
					</td></tr>
				<% end %>
			<% end %>
			<tr>
				<td colspan=5>
					<hr>
				</td>
			</tr>
		<% end %>
	<% end %>

<% end %>
</table>