config/routes.rb
MissionaryWebsite4::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/store'

  resources :contacts

  match 'aboutus-us' => 'home#aboutus', :via => [:get], :as => 'about_us'
  match 'privacy' => 'home#privacy', :via => [:get], :as => 'privacy'
  match 'warranty' => 'home#warranty', :via => [:get], :as => 'warranty'
  match 'resellers' => 'home#resellers', :via => [:get], :as => 'resellers'
  match 'almost_finished' => 'home#almost_finished', :via => [:get], :as => 'almost_finished'
  match '' => 'home#index', :via => [:get], :as => 'home'
  resources :hoggans_construction, :only => [:index, :update]
  resources :home do
    member do
      get 'price'
    end
  end
  root :to => 'home#index' 
end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :add_ons
    end
    resources :reports, :only => [] do
      collection do

        get   :idaho_taxes
        post  :idaho_taxes

      end
    end
    resources :workflows, :only => [:index, :update] do 
      collection do 
        put "update_all"
        get "authenticate"
        put "bluedot"
        get "oauth_callback"
        get "export_to_quickbooks"

      end
      member do
        get "packing_slip"
        get "shipping"
        post "rates"
        get "print_postage"
        post "purchase_postage"
        get "update_shipment"
        get "update_order"
        post 'show_to_hoggans'
        patch 'show_to_hoggans'
      end
    end
  end
end

  

app/views/spree/admin/shared/_add_on_product_tab.html.erb
<%= content_tag :li, class: (current == 'Add-Ons' ? 'active' : '') do %>
  <%= link_to_with_icon 'icon-star',
    Spree::AddOn.model_name.human(count: :many),
    admin_product_add_ons_url(@product)
  %>
<% end %>

app/views/spree/admin/shared/_orders_tab_override.html.erb
<li>
	<%= link_to_with_icon 'icon-c', Spree.t(:packing_slip), packing_slip_admin_workflow_path(@order) %>
</li>
<li>
	<%= link_to_with_icon 'icon-c', Spree.t(:print_postage), shipping_admin_workflow_path(@order.number) %>
</li>
<li>
	<%= link_to_with_icon 'icon-c', Spree.t(:update), update_order_admin_workflow_path(@order.number) %>
</li>

app/views/spree/admin/shared/_quickeebook_connector_button.html.erb
<% qc = QuickbooksConnection.first 
if qc && qc.token %>
	<%= configurations_sidebar_menu_item "Export to Quickbooks", export_to_quickbooks_admin_workflows_path %>
<% end %>
<li>
	<script type='text/javascript' src='https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js'></script>

	<!-- this will display a button that the user clicks to start the flow -->
	<ipp:connectToIntuit></ipp:connectToIntuit>
	
	<!-- configure the Intuit object: 'grantUrl' is a URL in your application which kicks off the flow, see below -->
	<script>
	$("connecttointuit").after("<ipp:connectToIntuit></ipp:connectToIntuit>");
	intuit.ipp.anywhere.setup({menuProxy: 'https://appcenter.intuit.com/api/v1/Account/AppMenu', grantUrl: '<%= authenticate_admin_workflows_url %>'});
	</script>

	
</li>

app/views/spree/admin/shared/_report_criteria.html.erb
<%= search_form_for @search, :url => url do |s| %>
    <div class="date-range-filter field align-center">
        <%= label_tag nil, Spree.t(:start), :class => 'inline' %>
        <%= s.text_field :created_at_gt, :class => 'datepicker datepicker-from', :value => datepicker_field_value(params[:q][:created_at_gt]) %>

        <span class="range-divider">
          <i class="icon-arrow-right"></i>
        </span>

        <%= s.text_field :created_at_lt, :class => 'datepicker datepicker-to', :value => datepicker_field_value(params[:q][:created_at_lt]) %>
        <%= label_tag nil, Spree.t(:end), :class => 'inline' %>
    </div>

    <div class="actions filter-actions">
      <%= button Spree.t(:search), 'icon-search'  %>
    </div>
<% end %>