config/routes.rb
MissionaryWebsite4::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/store'

  resources :contacts

  match 'aboutus-us' => 'home#aboutus', :via => [:get], :as => 'about_us'
  match 'privacy' => 'home#privacy', :via => [:get], :as => 'privacy'
  match 'warranty' => 'home#warranty', :via => [:get], :as => 'warranty'
  match 'resellers' => 'home#resellers', :via => [:get], :as => 'resellers'
  match 'almost_finished' => 'home#almost_finished', :via => [:get], :as => 'almost_finished'
  match '' => 'home#index', :via => [:get], :as => 'home'
  resources :hoggans_construction, :only => [:index, :update]
  resources :home do
    member do
      get 'price'
    end
  end
  root :to => 'home#index' 
end

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :add_ons
    end
    resources :reports, :only => [] do
      collection do

        get   :idaho_taxes
        post  :idaho_taxes

      end
    end
    resources :workflows, :only => [:index, :update] do 
      collection do 
        put "update_all"
        get "authenticate"
        put "bluedot"
        get "oauth_callback"
        get "export_to_quickbooks"

      end
      member do
        get "packing_slip"
        get "shipping"
        post "rates"
        get "print_postage"
        post "purchase_postage"
        get "update_shipment"
        get "update_order"
        post 'show_to_hoggans'
        patch 'show_to_hoggans'
      end
    end
  end
end

  

app/views/products/_pinterest_button.html.erb
<!-- Facebook SDK -->
<div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=327531060677996";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

<%
	my_image = Spree::Image.find(@product.images.first.id)
%>


<a href="https://pinterest.com/pin/create/button/
?url=<%= product_url(@product.slug)  %>
&media=<%= my_image.attachment.url(:product) %>
&description=Tough%20bags%20for%20missionaries." 
data-pin-do="buttonPin" 
data-pin-config="beside">
	<img src="https://assets.pinterest.com/images/pidgets/pin_it_button.png" />
</a>
  

<div class="fb-like" data-href="<%= product_url(@product.slug)  %>" data-send="false" data-layout="button_count" data-width="200" data-show-faces="true" data-font="lucida grande"></div>

<a href="https://twitter.com/share" class="twitter-share-button" data-hashtags="missionarybag">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/products/_product_availability.html.erb
<br><strong>Availability:</strong> 

<% if variant.in_stock? %>
	In-stock
<% else %>
	6-10 Business Days
<% end %>

app/views/products/_product_image.html.erb
<div class="product-image">

  <%= link_to product_image(product, :itemprop => "image"), url, :itemprop => 'url' %>

</div>

app/views/products/_products_header.html.erb
<div class="top-slider small">
	<img src="/assets/bags2.jpg">
</div>
<h2 class="center">Choose your exterior color</h2>

<h5 class="center grey centered-text">Here at Missionary Bags we strive to offer you the finest built bags, only using the finest materials and highest quality craftsmanship. Each of these bags is made with amazingly tough ballistic nylon.</h5>

app/views/products/_show_header.html.erb
<h2 class='center'><%= accurate_title %></h2>